name: "Discord Alert on Failure"

on:
  workflow_run:
    workflows: ["Update Trackers"] ে
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Discord Webhook Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "⚠️ **Warning:** The Automatic Trackers update workflow has failed! Please check the GitHub Actions logs."
