name: 🛡️ OpenSSF Scorecard Security

on:
  # For branch protection rules
  branch_protection_rule:
  # To run weekly on Saturday
  schedule:
    - cron: '30 1 * * 6'
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Only the latest analysis per branch matters
concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write

    steps:
      - name: "📥 Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "🔍 Run OpenSSF Scorecard analysis"
        uses: ossf/scorecard-action@v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          # Publish the results for public repositories to get the badge
          publish_results: true

      - name: "📦 Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      - name: "🛡️ Upload to Code-Scanning Dashboard"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
